# Generated by Django 4.1 on 2022-08-15 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=256)),
                ('cpf', models.IntegerField(max_length=11)),
                ('data_nascimento', models.DateField(null=True)),
                ('cargo', models.CharField(max_length=256)),
                ('ativa', models.BooleanField(default=True)),
            ],
        ),
    ]
