# Generated by Django 4.1 on 2022-08-22 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0004_funcionario_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='funcionario.funcionario'),
        ),
    ]
